apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ra6m1nkyg-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ra6m1nkyg-java-springboot-gitops